### ISSUE TITLE
[feature request] Export final image with round corners

### ISSUE THREAD

**Issue by BetaHuhn** [kangabru/pretty-snap#2]
Hey @kangabru 🦘 

I started to use [Pretty Snap](https://prettysnap.app/) for a few Mockups/Screenshots recently and it works great! It saves me a lot of time, which is always appreciated 😄 

One thing I would find useful though, is to export the final image with round corners, just like in the preview. Especially in READMEs I like the look of rounded corners and it would be great if [Pretty Snap](https://prettysnap.app/) had an option to do this automatically, instead of having to import the picture into Photoshop to adjust the corners manually.

As the picture gets exported as a PNG anyway, this would be an awesome addition! A simple button next to the alignment buttons or the padding slider would suffice.

Thank you for your great work on [Pretty Snap](https://prettysnap.app/) as well as [Panda Snap](https://pandasnap.io/)!

Cheers ✌

**Comment by kangabru** [comment]
Hey Maximilian!

Thanks for the great feedback and suggestion. 

Yeah that's a good use case. I always expected CSS to be available but that's not so easy in a readme. I'll investigate how feasible it is an try incorporate something in the next release.

Cheers,
Scotty

**Comment by kangabru** [comment]
Hey @BetaHuhn,

I just pushed an update to the dev build which now includes this feature.
- Try out the [dev build here](https://dev.prettysnap.app/#/)
- Access the option via the 'advanced' sections in either app (you'll have to select an image before the controls become visible)
- The setting should persist between refreshes

![image](https://user-images.githubusercontent.com/55638818/109444129-170a3400-7a02-11eb-96d4-862bedb21a21.png)

If you find any issues or think it needs some tweaking please let me know!

Thanks again for the suggestion.

**Comment by BetaHuhn** [comment]
Great!🎉 

It seems to work perfectly, I haven't found any issues yet!

Thanks again!
